/*
 * Test data strategy for lighting.sensor.LightListenerImpl.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2018-01-08 21:21 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package lighting.sensor;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for lighting.sensor.LightListenerImpl. Provides
 * instances of lighting.sensor.LightListenerImpl for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2018-01-08 21:21 +0200
 */
public /*@ nullable_by_default */ class LightListenerImpl_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of LightListenerImpl.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add lighting.sensor.LightListenerImpl values or generators here */ });
  }

  /**
   * @return default instances of LightListenerImpl, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<lighting.sensor.LightListenerImpl> defaultValues() {
    final List<RepeatedAccessIterator<lighting.sensor.LightListenerImpl>> iters = 
      new LinkedList<RepeatedAccessIterator<lighting.sensor.LightListenerImpl>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<lighting.sensor.LightListenerImpl>
      (lighting.sensor.LightListenerImpl.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method LightListenerImpl(LightingController)
    iters.add(new InstantiationIterator<lighting.sensor.LightListenerImpl>
      (lighting.sensor.LightListenerImpl.class, 
       new Class<?>[]
       {lighting.LightingController.class},
       LightListenerImpl_JML_Test.p_LightListenerImpl__LightingController_lightingController__9().wrapped()));

    return new NonNullMultiIterator<lighting.sensor.LightListenerImpl>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public LightListenerImpl_InstanceStrategy() {
    super(lighting.sensor.LightListenerImpl.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
